name: Update Daily Key from Website

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes UTC
  workflow_dispatch:

jobs:
  fetch-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch key from website
        run: |
          # Fetch website HTML
          HTML=$(curl -s https://nc-roblox.github.io/Daily-Key-Page/)

          # Extract the key from <div id="key">KEY</div>
          NEW_KEY=$(echo "$HTML" | grep -oP '(?<=<div id="key">)[^<]+')

          echo "Fetched key: $NEW_KEY"

          # Write key to dailykey.txt
          echo "$NEW_KEY" > dailykey.txt

          # Commit and push changes
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dailykey.txt
          git commit -m "Update daily key from website" --allow-empty
          git push
