name: Update Daily Key

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:

jobs:
  update-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update dailykey.txt
        run: |
          KEYS=("A1bX9kLq" "P3vN7zRt" "Q8mF2dWy" "L5sH4pVz" "G6rK1tBn" "T9xJ3vQc" "Z2fL8wPm" "H4yR6qSd" "V7cN0bXk" "M1jT5zLv")
          # Every 15 minutes index
          INDEX=$(( ($(date +%s) / 900) % 10 ))
          echo "${KEYS[$INDEX]}" > dailykey.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dailykey.txt
          git commit -m "Update daily key" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/<USERNAME>/<REPO>.git HEAD:main
