name: Update Key Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # every 1 minute UTC
  workflow_dispatch:

jobs:
  update-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set current key
        run: |
          KEYS=("K1aB9xZ1" "K2zP0qLm" "K3r8YtQw" "K4p9HnVc" "K5s5F4gT" "K6u7JkL2" "K7x1M0rN" "K8b4V6dE" "K9w2S8cY" "K10q0Z7t")
          MINUTE_NUMBER=$(( $(date -u +%s) / 60 ))
          INDEX=$(( MINUTE_NUMBER % ${#KEYS[@]} ))
          echo "${KEYS[$INDEX]}" > dailykey.txt

      - name: Commit updated key
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dailykey.txt
          git commit -m "Update daily key"
          git push
