name: Update Daily Key (3-Min Test)

on:
  schedule:
    - cron: '*/3 * * * *' # every 3 minutes
  workflow_dispatch:

jobs:
  update-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update dailykey.txt
        run: |
          # Define your 10 keys
          KEYS=("A1bX9kLq" "P3vN7zRt" "Q8mF2dWy" "L5sH4pVz" "G6rK1tBn" "T9xJ3vQc" "Z2fL8wPm" "H4yR6qSd" "V7cN0bXk" "M1jT5zLv")

          # 3-minute interval (UTC)
          INTERVAL=$(($(date +%s) / 180))  # 180 seconds = 3 minutes

          # Pseudo-random index based on interval (deterministic)
          INDEX=$(( (INTERVAL * 9301 + 49297) % ${#KEYS[@]} ))
          NEW_KEY="${KEYS[$INDEX]}"

          echo "Current interval: $INTERVAL"
          echo "Selected key: $NEW_KEY"

          # Write key to dailykey.txt
          echo "$NEW_KEY" > dailykey.txt

          # Commit and push changes
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dailykey.txt
          git commit -m "Auto-update daily key at interval $INTERVAL"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
