name: Update Daily Key

on:
  schedule:
    - cron: '*/1 * * * *' # every 1 minute
  workflow_dispatch:

jobs:
  update-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate today's key
        run: |
          keys=("A1bX9kLq" "P3vN7zRt" "Q8mF2dWy" "L5sH4pVz" "G6rK1tBn" "T9xJ3vQc" "Z2fL8wPm" "H4yR6qSd" "V7cN0bXk" "M1jT5zLv")
          minute=$(( $(date +%s) / 60 ))
          idx=$(( minute % ${#keys[@]} ))
          echo "${keys[$idx]}" > dailykey.txt
      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dailykey.txt
          git commit -m "Update key"
          git push
